using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;


namespace MetaSource;

/// <summary>
/// A sample source generator that creates a custom report based on class properties. The target class should be annotated with the 'Generators.ReportAttribute' attribute.
/// When using the source code as a baseline, an incremental source generator is preferable because it reduces the performance overhead.
/// </summary>
[Generator]
public class InstanceProviderIncrementalSourceGenerator : IIncrementalGenerator
{
    private const string Namespace = "MetaSource.Library.SourceGenerator";
    private const string AttributeName = "MetaDataAttribute";

    private const string AttributeSourceCode = $@"// <auto-generated/>

namespace {Namespace}
{{
    [System.AttributeUsage(System.AttributeTargets.Class)]
    public class {AttributeName} : System.Attribute
    {{
    }}
}}";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Add the marker attribute to the compilation.
        context.RegisterPostInitializationOutput(ctx => ctx.AddSource(
            "MetaDataAttribute.g.cs",
            SourceText.From(AttributeSourceCode, Encoding.UTF8)));

        // Filter classes annotated with the [Report] attribute. Only filtered Syntax Nodes can trigger code generation.
        var provider = context.SyntaxProvider
            .CreateSyntaxProvider(
                (s, _) => s is ClassDeclarationSyntax,
                (ctx, _) => GetClassDeclarationForSourceGen(ctx))
            .Where(t => t.reportAttributeFound)
            .Select((t, _) => t.Item1);

        // Generate the source code.
        context.RegisterSourceOutput(context.CompilationProvider.Combine(provider.Collect()),
            ((ctx, t) => GenerateCode(ctx, t.Left, t.Right)));
    }

    /// <summary>
    /// Checks whether the Node is annotated with the [Report] attribute and maps syntax context to the specific node type (ClassDeclarationSyntax).
    /// </summary>
    /// <param name="context">Syntax context, based on CreateSyntaxProvider predicate</param>
    /// <returns>The specific cast and whether the attribute was found.</returns>
    private static (ClassDeclarationSyntax, bool reportAttributeFound) GetClassDeclarationForSourceGen(
        GeneratorSyntaxContext context)
    {
        var classDeclarationSyntax = (ClassDeclarationSyntax) context.Node;

        // Go through all attributes of the class.
        foreach (AttributeListSyntax attributeListSyntax in classDeclarationSyntax.AttributeLists)
        foreach (AttributeSyntax attributeSyntax in attributeListSyntax.Attributes)
        {
            if (context.SemanticModel.GetSymbolInfo(attributeSyntax).Symbol is not IMethodSymbol attributeSymbol)
                continue; // if we can't get the symbol, ignore it

            string attributeName = attributeSymbol.ContainingType.ToDisplayString();

            // Check the full name of the [Report] attribute.
            if (attributeName == $"{Namespace}.{AttributeName}")
                return (classDeclarationSyntax, true);
        }

        return (classDeclarationSyntax, false);
    }

    /// <summary>
    /// Generate code action.
    /// It will be executed on specific nodes (ClassDeclarationSyntax annotated with the [Report] attribute) changed by the user.
    /// </summary>
    /// <param name="context">Source generation context used to add source files.</param>
    /// <param name="compilation">Compilation used to provide access to the Semantic Model.</param>
    /// <param name="classDeclarations">Nodes annotated with the [Report] attribute that trigger the generate action.</param>
    private void GenerateCode(SourceProductionContext context, Compilation compilation,
        ImmutableArray<ClassDeclarationSyntax> classDeclarations)
    {
        // Go through all filtered class declarations.
        foreach (var classDeclarationSyntax in classDeclarations)
        {
            // We need to get semantic model of the class to retrieve metadata.
            var semanticModel = compilation.GetSemanticModel(classDeclarationSyntax.SyntaxTree);

            // Symbols allow us to get the compile-time information.
            if (semanticModel.GetDeclaredSymbol(classDeclarationSyntax) is not INamedTypeSymbol classSymbol)
                continue;

            var namespaceName = classSymbol.ContainingNamespace.ToDisplayString();

            // 'Identifier' means the token of the node. Get class name from the syntax node.
            var className = classDeclarationSyntax.Identifier.Text;

            var accesibleProperties = classSymbol.GetMembers()
                .OfType<IPropertySymbol>()
                // filter to only return public or internal
                .Where(p => p.IsStatic == false &&  p.DeclaredAccessibility is Accessibility.Public or Accessibility.Internal)
                .ToList();

            foreach (var accessibleProperty in accesibleProperties)
            {
                var builder = new StringBuilder();

                builder.AppendLine("using MetaSource.Library;");
                builder.AppendLine($"namespace {namespaceName};");
                
                builder.AppendLine();
                
                // get display string that does not need a namespace from the type of the property
                var propertyType = accessibleProperty.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

                var propertyClassName = $"{className}_{accessibleProperty.Name}_InstanceProperty";
                
                builder.AppendLine(
                    $"public class {propertyClassName} : GenericInstancePropertyBase<{className}, {propertyType}>");
                builder.AppendLine("{");
                builder.AppendLine($"\tpublic override string Name => \"{accessibleProperty.Name}\";");
                builder.AppendLine();

                bool canRead = false;
                bool canWrite = false;

                if (accessibleProperty.IsReadOnly)
                {
                    canRead = true;
                }
                else if (accessibleProperty.IsWriteOnly)
                {
                    canWrite = true;
                }
                else
                {
                    canRead = true;
                    canWrite = true;
                }

                builder.AppendLine($"public override bool CanRead => {(canRead ? "true" : "false")};");
                builder.AppendLine($"public override bool CanWrite => {(canWrite ? "true" : "false")};");

                
                // Create GetValue method
                builder.AppendLine($"public override {propertyType} GetValue({className} source)");
                builder.AppendLine("{");

                if (canRead)
                {
                    builder.AppendLine($"return source.{accessibleProperty.Name};");
                }
                else
                {
                    builder.AppendLine("throw new System.NotSupportedException();");
                }
                
                builder.AppendLine("}");
                
                // Create SetValue method
                builder.AppendLine($"public override void SetValue({className} source, {propertyType} value)");
                builder.AppendLine("{");

                if (canWrite)
                {
                    builder.AppendLine($"source.{accessibleProperty.Name} = value;");
                }
                else
                {
                    builder.AppendLine("throw new System.NotSupportedException();");
                }
                
                builder.AppendLine("}");
                
                
                builder.AppendLine("}");
                
                // Add the source code to the compilation.
                context.AddSource($"{propertyClassName}.g.cs", SourceText.From(builder.ToString(), Encoding.UTF8));
            }

            
        }
    }
}